# Generated by Django 4.1 on 2022-12-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_repository_code_alter_repository_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='version',
            new_name='cTag',
        ),
    ]
