# Generated by Django 4.1 on 2022-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_version_repository_ctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='keepNumber',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='repository',
            name='serviceFilePath',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
