# Generated by Django 4.1 on 2022-12-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_repository_keepnumber_repository_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='startCommand',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
