# Generated by Django 4.1 on 2022-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_repository_startcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
