# Generated by Django 4.1 on 2022-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_repository_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='serviceFilePath',
        ),
        migrations.AddField(
            model_name='repository',
            name='fullName',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='repository',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
