# Generated by Django 4.1 on 2022-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_repository_servicefilepath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('Game', models.CharField(blank=True, default='', max_length=1000)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('fullName', models.CharField(blank=True, default='', max_length=300)),
                ('startCommand', models.CharField(blank=True, default='', max_length=300)),
                ('downloadURL', models.URLField(blank=True, default='')),
                ('connectionURL', models.CharField(blank=True, default='', max_length=1000)),
                ('code', models.CharField(blank=True, default='', max_length=300)),
                ('enable', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
