# Generated by Django 4.1 on 2022-12-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gameservers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameServers',
            new_name='GameServer',
        ),
    ]
